### ISSUE TITLE
Add me as collaborator

### ISSUE THREAD

**Issue by szhou1** [vasilionjea/ember-a11y-accordion#100]
Hi, @vasilionjea. I work with @ryanone at LinkedIn and would like to request if I can be made a collaborator as well. Seems like collaborators do not have permission to add other collaborators. Thanks!

**Comment by szhou1** [comment]
@vasilionjea @ryanone friendly bump :)

**Comment by vasilionjea** [comment]
@szhou1 What's your NPM handle at www.npmjs.com?

**Comment by szhou1** [comment]
@vasilionjea it's also `szhou1` 
https://www.npmjs.com/~szhou1

**Comment by vasilionjea** [comment]
Done! Apologies for the delay. Let me know if you need anything else.
