### ISSUE TITLE
role="heading" is not allowed on <header>

### ISSUE THREAD

**Issue by yc-shawn** [vasilionjea/ember-a11y-accordion#12]
Captured by axe a11y tool, `role="heading"` is not allowed on `<header>` element
Can we remove the `role="heading"`?

![Aria role](https://user-images.githubusercontent.com/23707313/83903352-d4d1f180-a712-11ea-9a10-4923c7341db0.png)

**Comment by vasilionjea** [comment]
Interesting find. 

The better solution would be to refactor the code (_if possible_) to make it so the **tagName** of the `accordion-header` component is dynamically generated by an option provided to it – maybe a `heading-level` option, which would be used as such: `{{#item.header heading-level="3"}}An h3 heading{{/item.header}}`. This would eliminate the Axe issue and also the need for the `aria-level="4"` option. This solution would require a major version bump. 

The easiest solution would be to change the **tagName** of the `accordion-header` component to a `div` and leave everything else as is. 

I don't write much Ember code these days so I'll accept a pull request for any of the solutions above.

**Comment by yc-shawn** [comment]
I think we can just simply change the <header> to <div> and keep rest the same.
And I'm not be able to make the pull request, I got this when I want to push my local branch:
```
fatal: unable to access 'https://github.com/vasilionjea/ember-a11y-accordion.git/': The requested URL returned error: 403
```

**Comment by ryanone** [comment]
Closing this out, as this was addressed in [this commit](https://github.com/vasilionjea/ember-a11y-accordion/commit/50b9abc95d8862679ae5502df6b498c51892abac)
