### ISSUE TITLE
Any plans to update to Octane?

### ISSUE THREAD

**Issue by ryanone** [vasilionjea/ember-a11y-accordion#13]
Hi - I'm wondering if it's on the roadmap to update the codebase in general, and get it up to date with things like Octane, etc.?

@vasilionjea Actually, if it helps, I forked the repo and updated to Octane and Ember 3.26. If you're willing to look at a PR, I can send one your way.

**Comment by vasilionjea** [comment]
@ryanone Thanks, and I'll happily accept a PR. I'll do a major version bump and if all looks good I'll republish to NPM.

**Comment by ryanone** [comment]
Thanks - I fired off PR #14. I appreciate you looking into the PR 👍🏼
